version: '3'
services:
  frontend:
    image: kapilguptansit/ecommerce-store-frontend:latest
    environment:
      CLOUDINARY_URL: $CLOUDINARY_URL
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: kapilguptansit/ecommerce-store-backend:latest
    environment:
      MONGO_SRV: $MONGO_SRV
      JWT_SECRET: $JWT_SECRET
      CLOUDINARY_URL: $CLOUDINARY_URL
      STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
      CLOUDWATCH_GROUP_NAME: $CLOUDWATCH_GROUP_NAME
      CLOUDWATCH_ACCESS_KEY: $CLOUDWATCH_ACCESS_KEY
      CLOUDWATCH_SECRET_ACCESS_KEY: $CLOUDWATCH_SECRET_ACCESS_KEY
      CLOUDWATCH_REGION: $CLOUDWATCH_REGION
      PORT: $PORT
    restart: always
    ports:
      - 8080:8080
